Nox Futura
rust-gamedev/arewegameyet pull request #355
Opened 2020-10-22 20:06 UTC by ozkriff

![image](https://user-images.githubusercontent.com/662976/96924333-2f4dcd80-14bb-11eb-8ceb-6801a733ec58.png)

@thebracket fyi

2020-10-22 20:40 UTC, 17cupsofcoffee approved these changes

2020-10-22 20:41 UTC, 17cupsofcoffee requested changes
Think that's an old repo, actually - https://github.com/thebracket/noxfutura is the Rust version.

2020-10-22 21:03 UTC, thebracket commented
That's correct, the Rust repo is: https://github.com/thebracket/noxfutura

Thanks for looking at the project!

2020-10-22 22:26 UTC, kvark approved these changes

2020-10-23 20:56 UTC, 17cupsofcoffee approved these changes
lgtm 👍

2020-10-23 21:06 UTC, merged